spring.application.name=gestionmascotas

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://ep-super-forest-aqe8goy1-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_mok63uiKQrlP

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true